DACSQLNS/Areas/Manager/Controllers/LeaveRequestsManagerController.cs
using DACSQLNS.Models;
using DACSQLNS.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;


namespace DACSQLNS.Areas.Manager.Controllers
{
    [Area("Manager")]
    [Authorize(Roles = SD.Role_Manager)]
    public class LeaveRequestsManagerController : Controller
    {
        private readonly ApplicationDbContext _context;
      


        public LeaveRequestsManagerController(ApplicationDbContext context)
        {
            _context = context;
            
        }

        public async Task<IActionResult> Index()
        {
            // Lấy danh sách tất cả các đơn xin nghỉ ở trạng thái đang xử lý
            var leaveRequests = await _context.LeaveRequests
                .Where(lr => lr.Status == "Đang chờ xử lý")
                .Include(lr => lr.ApplicationUser) // Đảm bảo rằng ApplicationUser đã được tải
                .ToListAsync();

            // Đếm số lượng đơn đang chờ xử lý và truyền qua ViewBag
            ViewBag.PendingApprovalCount = leaveRequests.Count;

            return View(leaveRequests);
        }


        public async Task<IActionResult> Approve(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leaveRequest = await _context.LeaveRequests.Include(lr => lr.ApplicationUser).FirstOrDefaultAsync(lr => lr.Id == id);
            if (leaveRequest == null)
            {
                return NotFound();
            }

            leaveRequest.Status = "Đã phê duyệt";
            leaveRequest.UpdatedDate = DateTime.Now;
            await _context.SaveChangesAsync();

            // Trích xuất thông tin từ đơn xin nghỉ phép đã được phê duyệt
            var employeeName = leaveRequest.ApplicationUser.FullName;
            var startDate = leaveRequest.StartTime.ToShortDateString();
            var endDate = leaveRequest.EndTime.ToShortDateString();
            var reason = leaveRequest.Reason;

            // Đường dẫn tới file template email HTML
            var templatePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Templates", "ApprovedLeaveRequest.html");

            // Đọc nội dung của template email
            string emailContent;
            try
            {
                emailContent = System.IO.File.ReadAllText(templatePath);
            }
            catch (Exception ex)
            {
                return Content($"Error reading template: {ex.Message}");
            }

            // Thay thế các placeholder trong template email bằng thông tin tương ứng từ đơn xin nghỉ phép
            emailContent = emailContent.Replace("[Employee's Name]", employeeName)
                                       .Replace("[Start Date]", startDate)
                                       .Replace("[End Date]", endDate)
                                       .Replace("[Reason]", reason);

            // Kiểm tra xem các giá trị đã được thay thế đúng cách chưa
            System.Diagnostics.Debug.WriteLine($"Email Content: {emailContent}");

            // Gửi email thông báo
            var result = clsMail.Send(leaveRequest.ApplicationUser.Email, "Đơn Xin Nghỉ Phép Đã Được Phê Duyệt", emailContent, "ApprovedLeaveRequest");
            if (result != "OK")
            {
                // Trả về nội dung lỗi
                return Content($"Error sending email: {result}");
            }

            return RedirectToAction(nameof(Index));
        }



        // Action để từ chối đơn xin nghỉ
        public async Task<IActionResult> Reject(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leaveRequest = await _context.LeaveRequests.Include(lr => lr.ApplicationUser).FirstOrDefaultAsync(lr => lr.Id == id);
            if (leaveRequest == null)
            {
                return NotFound();
            }

            leaveRequest.Status = "Bị từ chối";
            leaveRequest.UpdatedDate = DateTime.Now;
            await _context.SaveChangesAsync();

            // Trích xuất thông tin từ đơn xin nghỉ phép đã bị từ chối
            var employeeName = leaveRequest.ApplicationUser.FullName;
            var startDate = leaveRequest.StartTime.ToShortDateString();
            var endDate = leaveRequest.EndTime.ToShortDateString();
            var reason = leaveRequest.Reason;

            // Đường dẫn tới file template email HTML
            var templatePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Templates", "RejectedLeaveRequest.html");

            // Đọc nội dung của template email
            string emailContent;
            try
            {
                emailContent = System.IO.File.ReadAllText(templatePath);
            }
            catch (Exception ex)
            {
                return Content($"Error reading template: {ex.Message}");
            }

            // Thay thế các placeholder trong template email bằng thông tin tương ứng từ đơn xin nghỉ phép
            emailContent = emailContent.Replace("[Employee's Name]", employeeName)
                                       .Replace("[Start Date]", startDate)
                                       .Replace("[End Date]", endDate)
                                       .Replace("[Reason]", reason);

            // Gửi email thông báo
            var result = clsMail.Send(leaveRequest.ApplicationUser.Email, "Đơn Xin Nghỉ Phép Bị Từ Chối", emailContent, "RejectedLeaveRequest");
            if (result != "OK")
            {
                // Trả về nội dung lỗi
                return Content($"Error sending email: {result}");
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leaveRequest = await _context.LeaveRequests
                .Include(lr => lr.ApplicationUser)
                .FirstOrDefaultAsync(lr => lr.Id == id);

            if (leaveRequest == null)
            {
                return NotFound();
            }

            return View(leaveRequest);
        }
        public async Task<IActionResult> ApprovedRequests(int? month, int? year)
        {
            month ??= DateTime.Now.Month;
            year ??= DateTime.Now.Year;

            var approvedLeaveRequests = await _context.LeaveRequests
                .Where(lr => lr.Status == "Đã phê duyệt" && lr.StartTime.Month == month && lr.StartTime.Year == year)
                .Include(lr => lr.ApplicationUser)
                .ToListAsync();

            ViewBag.SelectedMonth = month;
            ViewBag.SelectedYear = year;

            return View(approvedLeaveRequests);
        }


        public async Task<IActionResult> RejectedRequests(int? month, int? year)
        {
            month ??= DateTime.Now.Month;
            year ??= DateTime.Now.Year;

            var rejectedLeaveRequests = await _context.LeaveRequests
                .Where(lr => lr.Status == "Bị từ chối" && lr.StartTime.Month == month && lr.StartTime.Year == year)
                .Include(lr => lr.ApplicationUser)
                .ToListAsync();

            ViewBag.SelectedMonth = month;
            ViewBag.SelectedYear = year;

            return View(rejectedLeaveRequests);
        }


    }
}

DACSQLNS/Areas/Manager/Views/LeaveRequestsManager/ApprovedRequests.cshtml
@model List<DACSQLNS.Models.LeaveRequest>

@{
    int selectedMonth = ViewBag.SelectedMonth;
    int selectedYear = ViewBag.SelectedYear;
    int totalRequests = Model.Count;
}

<h2>Leave Requests Approved History</h2>

<form method="get" asp-action="ApprovedRequests">
    <div class="form-group">
        <label for="month">Month:</label>
        <select id="month" name="month" class="form-control">
            @for (int m = 1; m <= 12; m++)
            {
                <option value="@m" selected="@(m == selectedMonth)">
                    @m
                </option>
            }
        </select>
    </div>
    <div class="form-group">
        <label for="year">Year:</label>
        <select id="year" name="year" class="form-control">
            @for (int y = DateTime.Now.Year; y >= DateTime.Now.Year - 10; y--)
            {
                <option value="@y" selected="@(y == selectedYear)">
                    @y
                </option>
            }
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Filter</button>
</form>

<p>Total Leave Requests: @totalRequests</p>

<table class="table">
    <thead>
        <tr>
            <th>STT</th>
            <th>User</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Reason</th>
            <th>Type</th>
            <th>Days Off</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Count; i++)
        {
            <tr onclick="window.location.href='@Url.Action("Details", "LeaveRequestsManager", new { id = Model[i].Id })'" style="cursor: pointer;">
                <td>@(i + 1)</td>
                <td>@Model[i].ApplicationUser.FullName</td>
                <td>@Model[i].StartTime.ToString("dd-MM-yyyy")</td>
                <td>@Model[i].EndTime.ToString("dd-MM-yyyy")</td>
                <td>@Model[i].Reason</td>
                <td>@Model[i].Type</td>
                <td>@Model[i].DaysOff</td>
            </tr>
        }
    </tbody>
</table>

<div>
    <a asp-action="Index">Back to List</a>
</div>

DACSQLNS/Areas/Manager/Views/LeaveRequestsManager/Details.cshtml
@model DACSQLNS.Models.LeaveRequest

<h2>Leave Request Details</h2>

<div>
    <h4>Leave Request Information</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">Full Name:</dt>
        <dd class="col-sm-10">@Model.ApplicationUser.FullName</dd>

        <dt class="col-sm-2">Start Time:</dt>
        <dd class="col-sm-10">@Model.StartTime</dd>

        <dt class="col-sm-2">End Time:</dt>
        <dd class="col-sm-10">@Model.EndTime</dd>

        <dt class="col-sm-2">Reason:</dt>
        <dd class="col-sm-10">@Model.Reason</dd>

        <dt class="col-sm-2">Type:</dt>
        <dd class="col-sm-10">@Model.Type</dd>

        <dt class="col-sm-2">Status:</dt>
        <dd class="col-sm-10">@Model.Status</dd>

        <dt class="col-sm-2">Created Date:</dt>
        <dd class="col-sm-10">@Model.CreatedDate</dd>

        <dt class="col-sm-2">Updated Date:</dt>
        <dd class="col-sm-10">@Model.UpdatedDate</dd>
        @if (!string.IsNullOrEmpty(Model.ImageUrl))
        {
            <dt class="col-sm-2">Evidence:</dt>
            <dd class="col-sm-10">
                <a href="#" id="evidenceLink" onclick="showEvidence()">View Evidence</a>
            </dd>
        }
    </dl>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<!-- Modal to display evidence image -->
<div id="evidenceModal" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Evidence</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <img id="evidenceImage" src="@Model.ImageUrl" alt="Evidence" style="max-width:100%; height:auto;" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        function showEvidence() {
            $('#evidenceModal').modal('show');
        }
    </script>
}

DACSQLNS/Areas/Manager/Views/LeaveRequestsManager/Index.cshtml
@model List<DACSQLNS.Models.LeaveRequest>

@{
    ViewData["Title"] = "Leave Requests";
}

<h1>Leave Requests Pending Approval</h1>
<div class="alert alert-primary" role="alert">
    There are <strong>@ViewBag.PendingApprovalCount</strong> leave requests pending approval.
</div>
<table class="table">
    <thead>
        <tr>
            <th>STT</th>
            <th>User</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Type</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Count; i++)
        {
            var leaveRequest = Model[i];
            <tr style="cursor: pointer;" onclick="window.location.href='@Url.Action("Details", "LeaveRequestsManager", new { id = leaveRequest.Id })'">
                <td>@(i + 1)</td>
                <td>@(leaveRequest.ApplicationUser?.FullName)</td>
                <td>@(leaveRequest.StartTime.ToShortDateString())</td>
                <td>@(leaveRequest.EndTime.ToShortDateString())</td>
                <td>@(leaveRequest.Type)</td>
                <td>
                    <a href="@Url.Action("Approve", "LeaveRequestsManager", new { id = leaveRequest.Id })" class="btn btn-success">Approve</a>
                    <a href="@Url.Action("Reject", "LeaveRequestsManager", new { id = leaveRequest.Id })" class="btn btn-danger">Reject</a>
                </td>
            </tr>
        }
    </tbody>
</table>

DACSQLNS/Areas/Manager/Views/LeaveRequestsManager/RejectedRequests.cshtml
@model List<DACSQLNS.Models.LeaveRequest>

@{
    int selectedMonth = ViewBag.SelectedMonth;
    int selectedYear = ViewBag.SelectedYear;
    int totalRequests = Model.Count;
}

<h2>Leave Requests Rejected History</h2>

<form method="get" asp-action="RejectedRequests">
    <div class="form-group">
        <label for="month">Month:</label>
        <select id="month" name="month" class="form-control">
            @for (int m = 1; m <= 12; m++)
            {
                <option value="@m" selected="@(m == selectedMonth)">
                    @m
                </option>
            }
        </select>
    </div>
    <div class="form-group">
        <label for="year">Year:</label>
        <select id="year" name="year" class="form-control">
            @for (int y = DateTime.Now.Year; y >= DateTime.Now.Year - 10; y--)
            {
                <option value="@y" selected="@(y == selectedYear)">
                    @y
                </option>
            }
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Filter</button>
</form>

<p>Total Leave Requests: @totalRequests</p>

<table class="table">
    <thead>
        <tr>
            <th>STT</th>
            <th>User</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Reason</th>
            <th>Type</th>
            <th>Days Off</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Count; i++)
        {
            <tr onclick="window.location.href='@Url.Action("Details", "LeaveRequestsManager", new { id = Model[i].Id })'" style="cursor: pointer;">
                <td>@(i + 1)</td>
                <td>@Model[i].ApplicationUser.FullName</td>
                <td>@Model[i].StartTime.ToString("dd-MM-yyyy")</td>
                <td>@Model[i].EndTime.ToString("dd-MM-yyyy")</td>
                <td>@Model[i].Reason</td>
                <td>@Model[i].Type</td>
                <td>@Model[i].DaysOff</td>
            </tr>
        }
    </tbody>
</table>

<div>
    <a asp-action="Index">Back to List</a>
</div>