DACSQLNS/Controllers/AssetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DACSQLNS.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace DACSQLNS.Controllers
{
    [Authorize]
    public class AssetsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public AssetsController(ApplicationDbContext context,UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Assets
        public async Task<IActionResult> Index()
        {
            var users = await _userManager.GetUserAsync(User);
            var applicationDbContext = await _context.Asset.Include(a => a.ApplicationUser).Where(a => a.isSTatus == true && a.UserId == users.Id).ToListAsync();
            return View(applicationDbContext);
        }

        // GET: Assets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var asset = await _context.Asset
                .Include(a => a.ApplicationUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (asset == null)
            {
                return NotFound();
            }

            return View(asset);
        }

        // GET: Assets/Create
       
    }
}

DACSQLNS/Views/Shared/_Layout.cshtml
@{
    // Kiểm tra xem trang hiện tại có phải là trang login hay không
    bool isLoginPage = Context.Request.Path.Equals("/Identity/Account/Login", StringComparison.OrdinalIgnoreCase);
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DACSQLNS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DACSQLNS.styles.css" asp-append-version="true" />
    <link href="m:\dacs_11\dacsqlns\views\shared\_layout.cshtml.css" rel="stylesheet" />
    <link href="~/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
</head>
<body>
    @if (!isLoginPage)
    {
        <!-- Hiển thị header nếu không phải là trang login -->
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="~/lib/images/Ảnh chụp màn hình 2024-05-13 183131.png" alt="DACSQLNS Logo" style="max-height: 45px;">
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>

                        </ul>
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </nav>

            
          <!--  <div class="sidebar" id="sidebar">
                <div class="sidebar-inner slimscroll">
                    <div class="sidebar-contents">
                        <div id="sidebar-menu" class="sidebar-menu">

                            <ul>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Owner" asp-action="Index">AddOwner</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Contract" asp-action="Index">Contracts</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="PayRoll" asp-action="Index">PayRoll</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Training" asp-action="Index">Training</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Assets" asp-action="Index">Assets</a>
                                </li>
                            </ul>

                        </div>
                    </div>
                </div>
            </div>
              -->
        </header>
    }



    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

 
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>