DACSQLNS/Models/LeaveRequest.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DACSQLNS.Models
{
    public class LeaveRequest
    {
        public LeaveRequest() { 
            StartTime = DateTime.Now;
            EndTime = DateTime.Now;
        }
        public int Id { get; set; }

        [Required]
        public string UserId { get; set; }

        [Required]
        public DateTime StartTime { get; set; }

        [Required]
        public DateTime EndTime { get; set; }

        [Required]
        [StringLength(1000)]
        public string Reason { get; set; }

        public AbsenceType? Type { get; set; }

        [Required]
        [StringLength(50)]
        public string Status { get; set; } = "Đang chờ xử lý";

        public DateTime CreatedDate { get; set; }

        public DateTime? UpdatedDate { get; set; }

        [ForeignKey("UserId")]
        public ApplicationUser? ApplicationUser { get; set; }
        // Thêm thuộc tính để lưu đường dẫn của file
        
        public string? ImageUrl { get; set; }
        
        public List<Image>? Images { get; set; }
        [NotMapped]
        public int DaysOff
        {
            get
            {
                return (EndTime.Date - StartTime.Date).Days + 1;
            }
        }
    }

    public enum AbsenceType
    {
        SickLeave, // Nghỉ ốm
        AnnualLeave, // Nghỉ phép hàng năm
        MaternityLeave, // Nghỉ thai sản
        UnpaidLeave, // Nghỉ không lương
        Other // Loại khác
    }
}

DACSQLNS/Controllers/LeaveRequestsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DACSQLNS.Models;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using System.Globalization;

namespace DACSQLNS.Controllers
{
    public class LeaveRequestsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public LeaveRequestsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            // Lấy UserId của người dùng hiện tại
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Lấy danh sách các đơn xin nghỉ của người dùng đó ở trạng thái đang xử lý
            var leaveRequests = await _context.LeaveRequests
                .Where(lr => lr.UserId == userId && lr.Status == "Đang chờ xử lý")
                .ToListAsync();

            return View(leaveRequests);
        }



        public IActionResult Create()
        {
            // Tạo một đối tượng LeaveRequest mới
            var leaveRequest = new LeaveRequest();

            // Thiết lập UserId từ thông tin người dùng hiện tại
            leaveRequest.UserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            return View(leaveRequest);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(LeaveRequest leaveRequest, IFormFile evidenceFile)
        {
            if (evidenceFile == null || evidenceFile.Length == 0)
            {
                ModelState.AddModelError("evidenceFile", "Evidence file is required.");
            }
            if (ModelState.IsValid)
            {
              
                if (evidenceFile != null && evidenceFile.Length > 0)
                {
                    // Lưu hình ảnh minh chứng
                    leaveRequest.ImageUrl = await SaveImage(evidenceFile);
                }
                leaveRequest.CreatedDate = DateTime.Now;
                leaveRequest.Status = "Đang chờ xử lý";
                await _context.LeaveRequests.AddAsync(leaveRequest);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            // Nếu ModelState không hợp lệ, hiển thị lại form và thông báo lỗi
            ViewBag.ErrorMessage = "Please upload the evidence file.";
            return View(leaveRequest);
        }
        private async Task<string> SaveImage(IFormFile image)
        {
            var savePath = Path.Combine("wwwroot/images", image.FileName); // Thay đổi đường dẫn theo cấu hình của bạn
            using (var fileStream = new FileStream(savePath, FileMode.Create))
            {
                await image.CopyToAsync(fileStream);
            }
            return "/images/" + image.FileName; // Trả về đường dẫn tương đối
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leaveRequest = await _context.LeaveRequests
                .Include(lr => lr.ApplicationUser)
                .FirstOrDefaultAsync(lr => lr.Id == id);

            if (leaveRequest == null)
            {
                return NotFound();
            }

            return View(leaveRequest);
        }
        public async Task<IActionResult> History(int? month, int? year)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            month ??= DateTime.Now.Month;
            year ??= DateTime.Now.Year;

            var leaveRequests = await _context.LeaveRequests
                .Where(lr => lr.UserId == userId && lr.Status != "Đang chờ xử lý" && lr.StartTime.Month == month && lr.StartTime.Year == year)
                .ToListAsync();

            var approvedLeaveRequests = leaveRequests
                .Where(lr => lr.Status == "Đã phê duyệt");

            int totalDaysOff = approvedLeaveRequests
                .Sum(lr => lr.DaysOff);

            ViewBag.TotalDaysOff = totalDaysOff;
            ViewBag.SelectedMonth = month;
            ViewBag.SelectedYear = year;

            return View(leaveRequests);
        }
         public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var leaveRequest = await _context.LeaveRequests
            .FirstOrDefaultAsync(m => m.Id == id);
        if (leaveRequest == null)
        {
            return NotFound();
        }

        return View(leaveRequest);
    }

    // POST: LeaveRequests/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var leaveRequest = await _context.LeaveRequests.FindAsync(id);
        if (leaveRequest != null)
        {
            _context.LeaveRequests.Remove(leaveRequest);
            await _context.SaveChangesAsync();
        }

        return RedirectToAction(nameof(Index));
    }


    }
}

DACSQLNS/Views/LeaveRequests/Create.cshtml
@model DACSQLNS.Models.LeaveRequest

<h2>Create Leave Request</h2>
@if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.ErrorMessage
    </div>
}
<form asp-action="Create" method="post" enctype="multipart/form-data">
    <div class="form-group" hidden>
        <label asp-for="UserId">User Id:</label>
        <input asp-for="UserId" class="form-control" readonly />
        <span asp-validation-for="UserId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="StartTime">Start Time:</label>
        <input asp-for="StartTime" class="form-control" type="date" />
        <span asp-validation-for="StartTime" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="EndTime">End Time:</label>
        <input asp-for="EndTime" class="form-control" type="date" />
        <span asp-validation-for="EndTime" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Reason">Reason:</label>
        <input asp-for="Reason" class="form-control" />
        <span asp-validation-for="Reason" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Type">Type:</label>
        <select asp-for="Type" class="form-control">
            <option value="SickLeave">Sick Leave</option>
            <option value="AnnualLeave">Annual Leave</option>
            <option value="MaternityLeave">Maternity Leave</option>
            <option value="UnpaidLeave">Unpaid Leave</option>
            <option value="Other">Other</option>
        </select>
        <span asp-validation-for="Type" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ImageUrl" class="control-label">Evidence File:</label>
        <input type="file" name="evidenceFile" class="form-control-file" />
        <span asp-validation-for="ImageUrl" class="text-danger"></span>
    </div>

    <div class="form-group">
        <a href="#" id="evidenceLink" style="display:none;" onclick="showEvidence()">View Evidence</a>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

<!-- Modal to display evidence image -->
<div id="evidenceModal" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Evidence</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <img id="evidenceImage" src="#" alt="Evidence" style="max-width:100%; height:auto;" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        document.querySelector('input[type="file"]').addEventListener('change', function (event) {
            var file = event.target.files[0];
            if (file) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#evidenceLink').show();
                    $('#evidenceImage').attr('src', e.target.result);
                };
                reader.readAsDataURL(file);
            } else {
                $('#evidenceLink').hide();
            }
        });

        function showEvidence() {
            $('#evidenceModal').modal('show');
        }
    </script>
}

DACSQLNS/Views/LeaveRequests/Delete.cshtml
@model DACSQLNS.Models.LeaveRequest

@{
    ViewData["Title"] = "Delete Leave Request";
}

<h1>Delete Leave Request</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Leave Request</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">Start Time</dt>
        <dd class="col-sm-10">@Model.StartTime</dd>

        <dt class="col-sm-2">End Time</dt>
        <dd class="col-sm-10">@Model.EndTime</dd>

        <dt class="col-sm-2">Reason</dt>
        <dd class="col-sm-10">@Model.Reason</dd>

        <dt class="col-sm-2">Type</dt>
        <dd class="col-sm-10">@Model.Type</dd>

        <dt class="col-sm-2">Status</dt>
        <dd class="col-sm-10">@Model.Status</dd>

        <dt class="col-sm-2">Created Date</dt>
        <dd class="col-sm-10">@Model.CreatedDate</dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <button type="submit" class="btn btn-danger">Delete</button>
        <a asp-action="Index" class="btn btn-secondary">Cancel</a>
    </form>
</div>

DACSQLNS/Views/LeaveRequests/Details.cshtml
@model DACSQLNS.Models.LeaveRequest

<h2>Leave Request Details</h2>

<div>
    <h4>Leave Request Information</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">Start Time:</dt>
        <dd class="col-sm-10">@Model.StartTime</dd>

        <dt class="col-sm-2">End Time:</dt>
        <dd class="col-sm-10">@Model.EndTime</dd>

        <dt class="col-sm-2">Reason:</dt>
        <dd class="col-sm-10">@Model.Reason</dd>

        <dt class="col-sm-2">Type:</dt>
        <dd class="col-sm-10">@Model.Type</dd>

        <dt class="col-sm-2">Status:</dt>
        <dd class="col-sm-10">@Model.Status</dd>

        <dt class="col-sm-2">Created Date:</dt>
        <dd class="col-sm-10">@Model.CreatedDate</dd>

        <dt class="col-sm-2">Updated Date:</dt>
        <dd class="col-sm-10">@Model.UpdatedDate</dd>
        @if (!string.IsNullOrEmpty(Model.ImageUrl))
        {
            <dt class="col-sm-2">Evidence:</dt>
            <dd class="col-sm-10">
                <a href="#" id="evidenceLink" onclick="showEvidence()">View Evidence</a>
            </dd>
        }
    </dl>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<!-- Modal to display evidence image -->
<div id="evidenceModal" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Evidence</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <img id="evidenceImage" src="@Model.ImageUrl" alt="Evidence" style="max-width:100%; height:auto;" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        function showEvidence() {
            $('#evidenceModal').modal('show');
        }
    </script>
}

DACSQLNS/Views/LeaveRequests/History.cshtml
@model List<DACSQLNS.Models.LeaveRequest>

@{
    int selectedMonth = ViewBag.SelectedMonth;
    int selectedYear = ViewBag.SelectedYear;
}

<h2>Leave Request History</h2>

<form method="get" asp-action="History">
    <div class="form-group">
        <label for="month">Month:</label>
        <select id="month" name="month" class="form-control">
            @for (int m = 1; m <= 12; m++)
            {
                <option value="@m" selected="@(m == selectedMonth)">
                    @m
                </option>
            }
        </select>
    </div>
    <div class="form-group">
        <label for="year">Year:</label>
        <select id="year" name="year" class="form-control">
            @for (int y = DateTime.Now.Year; y >= DateTime.Now.Year - 10; y--)
            {
                <option value="@y" selected="@(y == selectedYear)">
                    @y
                </option>
            }
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Filter</button>
</form>

<p>Total Days Off (Approved Requests): @ViewBag.TotalDaysOff</p>

<table class="table">
    <thead>
        <tr>
            <th>STT</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Reason</th>
            <th>Type</th>
            <th>Status</th>
            <th>Days Off</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Count; i++)
        {
            <tr onclick="window.location.href='@Url.Action("Details", "LeaveRequests", new { id = Model[i].Id })'" style="cursor: pointer;">
                <td>@(i + 1)</td>
                <td>@Model[i].StartTime.ToString("dd-MM-yyyy")</td>
                <td>@Model[i].EndTime.ToString("dd-MM-yyyy")</td>
                <td>@Model[i].Reason</td>
                <td>@Model[i].Type</td>
                <td>@Model[i].Status</td>
                <td>@Model[i].DaysOff</td>
            </tr>
        }
    </tbody>
</table>

<div>
    <a asp-action="Index">Back to List</a>
</div>

DACSQLNS/Views/LeaveRequests/Index.cshtml
@model List<DACSQLNS.Models.LeaveRequest>

<h2>Leave Requests in Processing</h2>

<table class="table">
    <thead>
        <tr>
            <th>STT</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Reason</th>
            <th>Type</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Count; i++)
        {
            <tr onclick="window.location.href='@Url.Action("Details", "LeaveRequests", new { id = Model[i].Id })'" style="cursor: pointer;">
                <td>@(i + 1)</td>
                <td>@Model[i].StartTime.ToString("dd-MM-yyyy ")</td>
                <td>@Model[i].EndTime.ToString("dd-MM-yyyy")</td>
                <td>@Model[i].Reason</td>
                <td>@Model[i].Type</td>
                <td>@Model[i].Status</td>
                <td>
                    <a asp-action="Delete" asp-route-id="@Model[i].Id" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>