DACSQLNS/Areas/Admin/Controllers/OwnerController.cs
using DACSQLNS.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using DACSQLNS.Repositories;

namespace DACSQLNS.Areas.Admin.Controllers
{

    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class OwnerController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IDeparmentReposity _deparmentReposity;
        private readonly ApplicationDbContext _context;

        public OwnerController(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager, ApplicationDbContext context, IDeparmentReposity deparmentReposity)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _context = context;
            _deparmentReposity = deparmentReposity;
        }



        public async Task<IActionResult> Index()
        {
            var currenUser = await _userManager.GetUserAsync(User);
            var userRoles = await _userManager.GetRolesAsync(currenUser);
            var users = await _userManager.Users.Where(u => u.Conpany == currenUser.Conpany  ).ToListAsync();
            return View(users);
        }
        [HttpGet]
        
        public async Task<IActionResult> Edit(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            // Lấy danh sách các phòng ban
            var departments = _context.Department.Where(d => d.IsDeleted == false).ToList();

            // Tạo SelectList chứa danh sách các phòng ban
            ViewBag.Department = new SelectList(departments, "Id", "DepartmentName");
            // Lấy danh sách các vai trò
            var roles = await _roleManager.Roles.ToListAsync();

            // Lấy vai trò của người dùng
            var userRoles = await _userManager.GetRolesAsync(user);

            // Truyền danh sách vai trò vào ViewBag
            ViewBag.Roles = new SelectList(roles, "Name", "Name", userRoles);

            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, string roleName, ApplicationUser updatedUser)
        {
            if (id != updatedUser.Id)
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);
     
            if (user == null)
            {
                return NotFound();
            }
            if (string.IsNullOrEmpty(roleName))
            {
                // Nếu không có vai trò nào được chọn, redirect lại trang Edit với thông báo lỗi
                ModelState.AddModelError("", "Please select a role.");
                return View(user);
            }

            // Cập nhật thông tin người dùng
            user.UserName = updatedUser.UserName;
            user.Email = updatedUser.Email;
            user.FullName = updatedUser.FullName;
            user.DepartmentId = updatedUser.DepartmentId;
            // Lấy vai trò hiện tại của người dùng
            var userRoles = await _userManager.GetRolesAsync(user);
       
            // Thêm vai trò mới cho người dùng và loại bỏ các vai trò cũ
            await _userManager.RemoveFromRolesAsync(user, userRoles.ToArray());
            await _userManager.AddToRoleAsync(user, roleName);
            //var a = await _userManager.GetRolesAsync(user);

            // Cập nhật thông tin người dùng vào cơ sở dữ liệu
            var result = await _userManager.UpdateAsync(user);

            if (!result.Succeeded)
            {
                // Xử lý lỗi nếu có
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
                return View(user);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]


        public IActionResult Add()
        {
            // Lấy danh sách các vai trò
            var roles = _roleManager.Roles.ToList();

            // Lấy danh sách các phòng ban
            var departments = _context.Department.Where(d => d.IsDeleted == false).ToList();

            // Tạo SelectList chứa danh sách các phòng ban
            ViewBag.Department = new SelectList(departments, "Id", "DepartmentName");

            // Truyền danh sách vai trò vào ViewBag
            ViewBag.Roles = new SelectList(roles, "Name", "Name");

            return View();
        }


        [HttpPost]
       
        public async Task<IActionResult> Add(ApplicationUser user, string roleName, string password)
        {
            // Lấy thông tin người dùng hiện tại
            var currentUser = await _userManager.GetUserAsync(User);

            // Kiểm tra nếu người dùng hiện tại không tồn tại
            if (currentUser == null)
            {
                return NotFound();
            }

            // Gán CompanyId cho người dùng mới là giống với CompanyId của người tạo
            user.Conpany = currentUser.Conpany;

            var result = await _userManager.CreateAsync(user, password);
            if (result.Succeeded)
            {
                user.EmailConfirmed = true;
                await _userManager.AddToRoleAsync(user, roleName);
                return RedirectToAction(nameof(Index));
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }

            // Lấy lại danh sách các vai trò nếu có lỗi
            var roles = _roleManager.Roles.ToList();
 
            ViewBag.Roles = new SelectList(roles, "Name", "Name");

            return View(user);
        }


        public async Task<IActionResult> Delete(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        [HttpPost, ActionName("DeleteConfirmed")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
          
            user.IsDelete = true;
         
            await _userManager.UpdateAsync(user);
            return RedirectToAction(nameof(Index));
        }
        [ActionName("RecycleBin")]
        public async Task<IActionResult> RecycleBin()
        {
            var userDelete = await _userManager.GetUserAsync(User);
            var deletedUsers = await _userManager.Users.Where(u => u.IsDelete == true && u.Conpany == userDelete.Conpany).ToListAsync();
            return View(deletedUsers);
        }

        [HttpPost, ActionName("Restore")]
        public async Task<IActionResult> Restore(string id)
        {
            var RestoreUser = await _userManager.FindByIdAsync(id);
            
                RestoreUser.IsDelete = false;
                await _userManager.UpdateAsync(RestoreUser);
            
            return Ok();
        }
   /*     [HttpPost, ActionName("GetId")]
         public async Task<IActionResult> GetIdUser(string id)
        {
            var userIDs = await _userManager.FindByIdAsync(id);
            return userIDs;
        }*/
    }
}

DACSQLNS/Areas/Admin/Views/Owner/Add.cshtml
@model DACSQLNS.Models.ApplicationUser
<div class="container">
    <div class="text-center mb-4">
        
        <img src="~/lib/images/add.png" alt="Logo" style="max-width: 200px; height: auto;">
    </div>

    <h2 class="text-center mb-4">Add Employee</h2>

    <form asp-action="Add" method="post" class="form-horizontal">
        <div class="form-group">
            <label asp-for="UserName">Username</label>
            <input asp-for="UserName" class="form-control" />
            <span asp-validation-for="UserName" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Email">Email</label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" id="password" name="password" class="form-control" />
        </div>

        <div class="form-group">
            <label for="role">Role</label>
            <select id="role" name="roleName" class="form-control">
                @foreach (var role in ViewBag.Roles)
                {
                    <option value="@role.Value">@role.Text</option>
                }
            </select>
        </div>

        <div class="form-group">
            <label for="department">Department</label>
            <select id="department" name="DepartmentName" class="form-control">
                <option value="">-- Select Department --</option>
                @foreach (var department in ViewBag.Department)
                {
                    <option value="@department.Value">@department.Text</option>
                }
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Add</button>
    </form>
</div>

<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f4f7f6;
        margin-top: 40px;
    }

    .container {
        width: 50%;
        margin: auto;
        background-color: #fff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .form-group {
        margin-bottom: 15px;
    }

    label {
        font-weight: bold;
        margin-bottom: 5px;
        display: block;
    }

    input[type="text"],
    input[type="email"],
    select {
        width: 100%;
        padding: 10px;
        border-radius: 4px;
        border: 1px solid #ddd;
        margin-bottom: 10px;
    }

    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
        width: 100%;
        padding: 10px;
        border-radius: 4px;
        font-size: 16px;
    }

        .btn-primary:hover {
            background-color: #0056b3;
            border-color: #0056b3;
        }
</style>

DACSQLNS/Areas/Admin/Views/Owner/Edit.cshtml
@model ApplicationUser

<h2 class="text-center mb-4">Edit User</h2>

<form asp-action="Edit" method="post">
    <input type="hidden" asp-for="Id" />

    <div class="container">
        <div class="text-center mb-4">

            <img src="~/lib/images/add.png" alt="Logo" style="max-width: 200px; height: auto;">
        </div>
        <div class="form-group">
            <label asp-for="UserName">Username</label>
            <input asp-for="UserName" class="form-control" />
            <span asp-validation-for="UserName" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Email">Email</label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="FullName">Full Name</label>
            <input asp-for="FullName" class="form-control" />
            <span asp-validation-for="FullName" class="text-danger"></span>
        </div>

        @if (!User.IsInRole("Employee"))
        {
            <div class="form-group">
                <label for="role">Role</label>
                <select id="role" name="roleName" class="form-control">
                    @foreach (var role in ViewBag.Roles)
                    {
                        <option value="@role.Value">@role.Text</option>
                    }
                </select>
            </div>

            <div class="form-group">
                <label for="department">Department</label>
                <select id="department" name="DepartmentId" class="form-control">
                    <option value="">-- Select Department --</option>
                    @foreach (var department in ViewBag.Department)
                    {
                        <option value="@department.Value">@department.Text</option>
                    }
                </select>
            </div>
        }

        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>

<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f4f7f6;
        margin-top: 40px;
    }

    .container {
        width: 50%;
        margin: auto;
        background-color: #fff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .form-group {
        margin-bottom: 15px;
    }

    label {
        font-weight: bold;
        margin-bottom: 5px;
        display: block;
    }

    input[type="text"],
    input[type="email"],
    select {
        width: 100%;
        padding: 10px;
        border-radius: 4px;
        border: 1px solid #ddd;
        margin-bottom: 10px;
    }

    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
        width: 100%;
        padding: 10px;
        border-radius: 4px;
        font-size: 16px;
    }

        .btn-primary:hover {
            background-color: #0056b3;
            border-color: #0056b3;
        }
</style>

DACSQLNS/Areas/Admin/Views/Owner/Index.cshtml
@model IEnumerable<DACSQLNS.Models.ApplicationUser>
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quản Lý Người Dùng</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        .container {
            width: 80%;
            margin: auto;
        }

        .user-list {
            margin-top: 20px;
        }

        .card {
            border: 2px solid #ddd;
            border-radius: 10px;
            transition: border-color 0.3s ease;
        }

            .card:hover {
                border-color: rgba(0, 0, 0, 0.1);
            }

        .btn {
            padding: 0.375rem 0.75rem;
            border: none; /* Loại bỏ viền */
            border-radius: 0.25rem;
            color: black;
            background-image: linear-gradient(to right, #18A5A7, #B6C0C5);
            transition: background-color 0.3s, transform 0.2s;
            display: inline-block;
            text-decoration: none;
            cursor: pointer;
        }

            .btn:hover {
                background-color: #B6C0C5;
                color: white;
                transform: translateY(-2px);
            }

        .card-count {
            background-color: #007bff;
            color: white;
            border-radius: 10px;
            padding: 10px;
        }


        .card-list {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
        }

            .card-list .card {
                width: calc(33.33% - 10px); /* 10px là margin giữa các card */
                margin-bottom: 20px;
            }

        .action-buttons .btn {
            width: calc(33.33% - 10px); /* 10px là margin giữa các nút */
        }

        .custom-height {
            height: 93px; /* Ví dụ: đặt chiều cao là 200px */
        }

        /* Áp dụng class mới cho nút C và D */
        .fill1, .fill2, .fill3, .fill4 {
            height: 100px; /* Đặt chiều cao cố định */
            width: auto; /* Tự động tính toán chiều rộng dựa trên tỷ lệ khung hình gốc của ảnh */
            width: 193px; /* Đặt chiều rộng tối đa */
            padding: 0;
            border: 2px solid #ddd; /* Thêm viền với độ dày 2px và màu xám nhạt */
            border-radius: 10px; /* Bo tròn các góc */
            box-sizing: border-box; /* Đảm bảo kích thước tính toán bao gồm cả padding và border */
            overflow: hidden; /* Ẩn phần nằm ngoài khung */
            position: relative; /* Để căn chỉnh ảnh */
        }

            .fill1 img, .fill2 img, .fill3 img, .fill4 img {
                width: auto; /* Tự động tính toán chiều rộng của ảnh */
                height: 90%; /* Chiều cao tối đa là 100% của khung */
                object-fit: contain; /* Ảnh sẽ được thu nhỏ hoặc phóng to sao cho nó vẫn fit trong khung mà không bị giãn ra */
                position: absolute; /* Để căn giữa ảnh */
                top: 50%; /* Đặt top ở giữa */
                left: 50%; /* Đặt left ở giữa */
                transform: translate(-50%, -50%); /* Dịch chuyển ảnh điều chỉnh để căn giữa */
            }

    </style>

</head>
<body>
    <div class="container">
        <div class="user-list">
            <div class="card mb-4">
                <div class="card-body d-flex justify-content-between align-items-center">
                    <h4 class="mb-0">Danh Sách Người Dùng</h4>

                </div>

            </div>


            <div class="row mb-4">
                @if (!User.IsInRole("Employee"))
                {
                    <!-- Thêm Người Dùng -->
                    <div class="col-xl-3 col-sm-6 col-12">
                        <a class="card board1 fill1" asp-area="Admin" asp-controller="Owner" asp-action="Add">
                            <div class="card-body">
                                <div class="card_widget_header">
                                </div>
                                <div class="card_widget_img">
                                    <img src="~/lib/images/add-user.png" alt="card-img" />
                                </div>
                            </div>
                        </a>
                    </div>
                    <!-- Thùng Rác -->
                    <div class="col-xl-3 col-sm-6 col-12">
                        <a class="card board1 fill2" asp-area="Admin" asp-controller="Owner" asp-action="RecycleBin">
                            <div class="card-body">
                                <div class="card_widget_header">
                                </div>
                                <div class="card_widget_img">
                                    <img src="~/lib/images/delete.png " alt="card-img" />
                                </div>
                            </div>
                        </a>
                    </div>
                    <!-- Danh sách -->
                    <div class="col-xl-3 col-sm-6 col-12">
                        <button class="card board1 fill3 switch-list-view" data-view="card">
                            <div class="card-body">
                                <div class="card_widget_header">
                                </div>
                                <div class="card_widget_img">
                                    <img src="~/lib/images/list.png " alt="card-img" />
                                </div>
                            </div>
                        </button>
                    </div>
                    <!-- Card -->
                    <div class="col-xl-3 col-sm-6 col-12">
                        <button class="card board1 fill4 switch-list-view" data-view="list">
                            <div class="card-body">
                                <div class="card_widget_header">
                                </div>
                                <div class="card_widget_img">
                                    <img src="~/lib/images/id-card (1).png" alt="card-img" />
                                </div>
                            </div>
                        </button>
                    </div>
                }
            </div>


            <div class="card mb-4 custom-card-width">
                <div class="card-body d-flex justify-content-between align-items-center">
                    <h5 class="mb-0">People: @Model.Count()</h5>

                </div>
            </div>
            <!-- Hiển thị danh sách người dùng dưới dạng card -->
            <div class="card-list">
                @foreach (var user in Model)
                {
                    <div class="card mb-4">
                        <div class="card-body">
                            <h5 class="card-title">@user.FullName</h5>
                            <p class="card-text"><strong>Tên Đăng Nhập:</strong> @user.UserName</p>
                            <p class="card-text">
                                <strong>Vai Trò:</strong>
                                @foreach (var role in await UserManager.GetRolesAsync(user))
                                {
                                    <span class="badge badge-primary">@role</span>
                                }
                            </p>
                            <div class="action-buttons">
                                <a class="btn btn-primary" asp-area="Admin" asp-controller="Owner" asp-action="Edit" asp-route-id="@user.Id">Edit</a>
                                <a class="btn btn-black" asp-area="Admin" asp-controller="Payroll" asp-action="Index" asp-route-id="@user.Id">contract</a>
                                <a class="btn btn-danger delete-link" data-id="@user.Id">Delete</a>
                            </div>
                        </div>
                    </div>
                }
            </div>
            <!-- Kết thúc hiển thị danh sách người dùng dưới dạng card -->
            <div class="card">
                <table class="table mb-0">
                    <thead>
                        <tr>
                            <th>Họ Tên</th>
                            <th>Tên Đăng Nhập</th>
                            <th>Vai Trò</th>
                            <th>Hành Động</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var user in Model)
                        {
                            <tr class="category-row">
                                <td>@user.FullName</td>
                                <td>@user.UserName</td>
                                <td>
                                    @foreach (var role in await UserManager.GetRolesAsync(user))
                                    {
                                        <span class="badge badge-primary">@role</span>
                                    }
                                </td>
                                <td class="action-buttons">
                                    <a class="btn btn-primary" asp-area="Admin" asp-controller="Owner" asp-action="Edit" asp-route-id="@user.Id">Edit</a>
                                    <a class="btn btn-black" asp-area="Admin" asp-controller="Payroll" asp-action="Index" asp-route-id="@user.Id">contract</a>
                                    <a class="btn btn-danger delete-link" data-id="@user.Id">Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(function () {
            $(".delete-link").click(function () {
                if (confirm("Are you sure you want to delete this item?")) {
                    var id = $(this).data("id");
                    var row = $(this).closest("tr");
                    $.ajax({
                        type: "POST",
                        url: "/Owner/Delete",
                        data: { id: id },
                        success: function () {
                            row.remove();
                        },
                        error: function (xhr, status, error) {
                            console.error(xhr.responseText);
                        }
                    });
                }
            });

            $(".switch-list-view").click(function () {
                var view = $(this).data("view");
                if (view === "list") {
                    $(".card-list").show();
                    $(".table").hide();
                } else {
                    $(".card-list").hide();
                    $(".table").show();
                }
            });
        });
    </script>
</body>
</html>

DACSQLNS/Areas/Admin/Views/Owner/RecycleBin.cshtml
@model IEnumerable<DACSQLNS.Models.ApplicationUser>

<h2 class="text-center mb-4">Recycle Bin</h2>

<div class="container">
    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Name</th>
                <th scope="col">Phone Number</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var user in Model)
            {
                <tr>
                    <td>@user.Id</td>
                    <td>@user.Email</td>
                    <td>@user.FullName</td>
                    <td>
                        <div class="btn-group" role="group" aria-label="Actions">
                           
                            <a href="#" class="btn btn-success restore-link" data-id="@user.Id">Restore</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div class="container text-center">
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

@section Scripts {
    <script>
        $(function () {
            $(".restore-link").click(function () {
                if (confirm("Are you sure you want to restore this item?")) {
                    var id = $(this).data("id");
                    var row = $(this).closest("tr");
                    $.ajax({
                        type: "POST",
                        url: "/Owner/Restore",
                        data: { id: id },
                        success: function () {
                            row.remove();
                        },
                        error: function (xhr, status, error) {
                            console.error(xhr.responseText);
                        }
                    });
                }
            });
        });
    </script>
}